SELECT *
FROM restaurant.cuisine;
SELECT *
FROM restaurant.menu;
SELECT *
FROM restaurant.registration;
SELECT *
FROM restaurant.staff;
SELECT *
FROM restaurant.staff_cuisine;
SELECT *
FROM restaurant.orders;
SELECT *
FROM restaurant.orders_details;