-- TRUNCATE TABLE restaurant.staff;
INSERT INTO restaurant.staff
VALUES ('STAFF-01', 'Kat');
INSERT INTO restaurant.staff
VALUES ('STAFF-02', 'Kat');
INSERT INTO restaurant.staff
VALUES ('STAFF-03', 'Taro');
INSERT INTO restaurant.staff
VALUES ('STAFF-04', 'Owens');
INSERT INTO restaurant.staff
VALUES ('STAFF-05', 'Migi');
INSERT INTO restaurant.staff
VALUES ('STAFF-06', 'Dari');
INSERT INTO restaurant.staff
VALUES ('STAFF-07', 'Ida');
INSERT INTO restaurant.staff
VALUES ('STAFF-08', 'Neyu');
INSERT INTO restaurant.staff
VALUES ('STAFF-09', 'Rodion');
INSERT INTO restaurant.staff
VALUES ('STAFF-10', 'Neon');
INSERT INTO restaurant.staff
VALUES ('STAFF-11', 'Evan');
INSERT INTO restaurant.staff
VALUES ('STAFF-12', 'Gerion');