-- TRUNCATE TABLE restaurant.staff_cuisine;
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-01', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-01', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-02', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-02', 'Chinese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-03', 'Vietnamese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-03', 'Chinese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-03', 'Indian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-03', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-04', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-04', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-05', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-05', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-05', 'Vietnamese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-06', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-06', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-06', 'Chinese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-06', 'Indian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-06', 'Vietnamese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-07', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-07', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-07', 'Vietnamese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-07', 'Chinese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-08', 'Vietnamese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-08', 'Chinese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-08', 'Indian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-08', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-09', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-09', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-10', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-11', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-11', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-11', 'Vietnamese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-11', 'Chinese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-11', 'Indian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-12', 'Indonesian');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-12', 'German');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-12', 'Vietnamese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-12', 'Chinese');
INSERT INTO restaurant.staff_cuisine
VALUES ('STAFF-12', 'Indian');